# Generated Behave Feature File from FlowSphere Configuration
# This file was auto-generated by FlowSphere MCP Server
# Configuration: User API Test
# Generated: 2025-10-28T00:15:14.624379

Feature: User API Test
Test user registration and login

  Scenario: Get all users
    When I execute GET request to "/users"    Then the response status code should be 200
    And I extract "[0].id" as "firstUserId"


  Scenario: Get specific user details
    When I execute GET request to "/users/{{ .vars.firstUserId }}"    Then the response status code should be 200
    And the response field "id" should be "{{ .vars.firstUserId }}"


  Scenario: Create a new post
    When I execute POST request to "/posts" with body    And I set the request body to:
      """
      {
      "body": "Created at {{ $timestamp }}",
      "title": "Test Post {{ $guid }}",
      "userId": 1
}
      """
    Then the response status code should be 201
    And the response field "title" should be "Test Post"
