# Generated Behave Feature File from FlowSphere Configuration
# This file was auto-generated by FlowSphere MCP Server
# Configuration: Simple API Test
# Generated: 2025-10-27T23:39:25.698548

Feature: Simple API Test
Basic GET and POST requests

  Scenario: Get a single post
    When I execute GET request to "/posts/1"    Then the response status code should be 200


  Scenario: Create a new post
    When I execute POST request to "/posts" with body    And I set the request body to:
      """
      {
      "body": "This is a test post",
      "title": "Test Post",
      "userId": 1
}
      """
    Then the response status code should be 201
    And the response field "title" should be "Test Post"


  Scenario: Get all posts
    When I execute GET request to "/posts"    Then the response status code should be 200
